### ISSUE TITLE
Finetuning Next-T2I results in corrupted models?

### ISSUE THREAD

**Issue by megatomik** [Alpha-VLLM/Lumina-T2X#117]
Using the settings yaml file provided, except modifying these at the top (since they were empty) and modifying `scale_watershed `to `scaling_watershed`:

```
- settings:

  model:
    ckpt: "/workspace/SFT" #downloaded from Alpha-VLLM/Lumina-Next-SFT repo
    ckpt_lm: "google/gemma-2b"
    token: ""
...
```

and using the command

`lumina_next infer -c "/workspace/Lumina-T2X/lumina_next_t2i/configs/infer/settings.yaml" "a snow man" "./outputs"`

Produces this picture:

![Image](https://github.com/user-attachments/assets/4d2773ed-7427-4b7b-9300-d64e29f29181)

But finetuning for even 1 step and converting the checkpoints using the provided script results in this:

![Image](https://github.com/user-attachments/assets/65bf4bb9-7dce-43a1-88c3-3b31aa228da4)
